name: Build and Deploy to GAE

on:
  push:
    branches:
      - master

jobs:
  setup-build-publish-deploy:
    name: Setup, Build and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Setup gcloud CLI
    - name: Setup
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - run: |-
        gcloud info

    # Deploy the application to the GAE
    - name: Deploy
      uses: google-github-actions/deploy-appengine@main
      with:
        deliverables: '${{ github.workspace }}/src/main/webapp/WEB-INF/appengine-web.xml'
        project_id: ${{ secrets.GCP_PROJECT }}
